### ISSUE TITLE
타입스크팁트 지원

### ISSUE THREAD

**Issue by devunt** [huskyhoochu/num-to-korean#28]
`.d.ts` 파일이 없는 것으로 보이는데 추가된다면 타입스크립트에서도 사용이 가능할 것으로 보입니다 🎉

**Comment by huskyhoochu** [comment]
이슈 감사합니다! 이번 주말 안에 수정해보도록 하겠습니다!

**Comment by huskyhoochu** [comment]
`v.0.5.2` 버전부터 해당 이슈 해결되었습니다! 감사합니다.
