### ISSUE TITLE
Format 옵션에 특정단위 치환 옵션 건의

### ISSUE THREAD

**Issue by sjh836** [huskyhoochu/num-to-korean#32]
안녕하세요? lib 잘쓰고있습니다

아래와 같은 foramt 옵션 건의드려봅니다.

* 12000 -> 1.2만
* 12345 -> 1.2345만
* 12345 -> 1.2만 (자릿수 옵션)

감사합니다!

**Comment by huskyhoochu** [comment]
안녕하세요, 이렇게 프로젝트 건의를 해 주셔서 정말 감사드립니다.

몇 년 전에 제작해본 뒤에 유지보수를 놓고 있었는데 건의해 주신 부분 대로 추가 개발을 해보도록 하겠습니다.

개발 완료되면 이슈에 코멘트 드리겠습니다.

영감과 동기부여를 주셔서 감사합니다!

승형수 드림.

**Comment by huskyhoochu** [comment]
@sjh836 정말 죄송합니다. 드릴 말씀이 없네요. 그간 개인 사정으로 프로젝트를 돌보지 못했습니다.
이제부터는 진짜로 다시 시작해보려 합니다. 조금만 기다려주세요!

**Comment by huskyhoochu** [comment]
@sjh836  안녕하세요, 제작하다보니 소수점 옵션에 대해선 좀 어려움이 있었습니다.
만, 억, 조, 경 등 단위수에 의한 변환은 가능했는데,
십,백,천 등 반복 자릿수의 경우 어디까지 표현해야 할까? 가 의문이었습니다.

가령 12345 -> 1.2345만 이라면, 이건 숫자가 보유한 단위수 중 가장 큰 것을 따른다는 규칙이 금방 나옵니다.

그럼 1만 이하 숫자들은 자릿수를 기준으로 같은 규칙을 적용하면 어떨까 생각 중입니다.
- 1234 -> 1.234천
- 123 -> 1.23백
- 12 -> 1.2십 (?) 이건 좀 아니겠죠? <- 여기까지 해야될지 말아야될지도 고민입니다.

처음 생각하신 의견 있으시면 말씀 부탁드려요!

**Comment by huskyhoochu** [comment]
@sjh836 안녕하세요, 우선 천,백,십의 단위까지 모두 가능한 버전으로 먼저 배포했습니다.
의견 주시면 다음 버전에서 개량해보겠습니다.
